import json

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import time

chrome_options=Options()
chrome_options.add_argument('--headless')
"""最终的效果：不会弹出浏览器窗口"""

driver = webdriver.Chrome(executable_path='C:/Users/10211/Desktop/chromedriver.exe')
url = "https://www.nike.com/login"



def get_token(username, password):

    driver.get(url)
    time.sleep(5)


    # driver.find_element_by_xpath("//*[@id='470b411b-fb64-42d0-8b1d-411d3b0ee693']").click()

    email_input = driver.find_element_by_xpath("//input[@name='emailAddress']")
    email_input.clear()
    email_input.send_keys(username)

    password_input = driver.find_element_by_xpath("//input[@name='password']")
    password_input.clear()
    password_input.send_keys(password)
    # password_input.send_keys('Q')
    # password_input.send_keys('Q')
    # password_input.send_keys('Q')
    # password_input.send_keys('Q')
    # password_input.send_keys('Q')
    # password_input.send_keys('Q')
    # password_input.send_keys('Q')

    time.sleep(5)

    # driver.find_element_by_xpath("//input[@value='登录']").click()
    driver.find_element_by_xpath("//input[@value='SIGN IN']").click()
    time.sleep(5)

    #重新登录
    num_retries_attempted = 0
    num_retries = 5
    while True:
        try:
            # Xpath to error dialog button
            xpath = "/html/body/div[2]/div[3]/div[3]/div/div[2]/input"
            time.sleep(10)
            driver.find_element_by_xpath(xpath).click()

            password_input = driver.find_element_by_xpath("//input[@name='password']")
            password_input.clear()
            password_input.send_keys(password)

            driver.find_element_by_xpath("//input[@value='SIGN IN']").click()
        except Exception as e:
            break




    time.sleep(5)

    # wait_until_visible(driver=driver, xpath="//a[@data-path='myAccount:greeting']")

    driver.get("https://unite.nike.com/session.html")
    time.sleep(5)


    # token = {"user_id":"07833e4b-59e6-4826-8ec8-fa06661f516c","access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImFlYmJkMWMyLTNjNDUtNDM5NS04MGMzLWE3YTIyMmJlOTJmMHNpZyJ9.eyJ0cnVzdCI6MTAwLCJpYXQiOjE2MTA4ODQ2MTEsImV4cCI6MTYxMDg4ODIxMSwiaXNzIjoib2F1dGgyYWNjIiwianRpIjoiNDZmODI3ODktNzAwMi00MmRkLWI5ODMtNWRmZTdhMjJjOWZiIiwibGF0IjoxNjEwODg0NjExLCJhdWQiOiJjb20ubmlrZS5kaWdpdGFsIiwic3ViIjoiY29tLm5pa2UuY29tbWVyY2UubmlrZWRvdGNvbS53ZWIiLCJzYnQiOiJuaWtlOmFwcCIsInNjcCI6WyJuaWtlLmRpZ2l0YWwiXSwicHJuIjoiMDc4MzNlNGItNTllNi00ODI2LThlYzgtZmEwNjY2MWY1MTZjIiwicHJ0IjoibmlrZTpwbHVzIn0.1b8e-jpkQVEJcBj2weSoM8rMGQKuhQOJQAYjLKihxqnwZ5XxKVJtLPEMGzEF65WE6oD6wdfGWctFPZwaJPVaGUPH4zuU4tqbfAZw-dY6D_UJMI96uP9cGf4Ind6XAtSHH2migRRlA-9NGrNj2S0jn0iIcmjTCR-5MzaERSFHsyibIR16d_kXDHWe4kZz-owGDPraDE5j8rL_Z5V-yHA0TtUqzQBKRhUYJoBueNUdCbbNl2fiOTOgbXdqnbHgwWAAxvS0Dm4crS79p5dOIBeGYBzqTYDA6l9BQhKEuZx1QkCPiEL4ZFlNHE81n1rjIrMUDT7-4jX8DZ8JMuvSqAgMJg","refresh_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImE5ZjNhOThmLThiMTItNGIwYy1hNTVmLWFiNTVhMWM3MzhmYnNpZyJ9.eyJ0cnVzdCI6MTAwLCJpYXQiOjE2MTA4ODQ2MTEsImV4cCI6MTY0MjQyMDYxMSwiaXNzIjoib2F1dGgyaWR0IiwianRpIjoiMmNmNjFmMDctODU1Ni00Nzk5LWFlN2ItZTY0NjIyN2M5ZDk5IiwibGF0IjoxNjEwODg0NjExLCJhdWQiOiJvYXV0aDJpZHQiLCJjbGkiOiJIbEhhMkNqZTNjdGxhT3FueHZnWlhOYUFzN1Q5bkF1SCIsInN1YiI6IjA3ODMzZTRiLTU5ZTYtNDgyNi04ZWM4LWZhMDY2NjFmNTE2YyIsInNidCI6Im5pa2U6cGx1cyJ9.Ux-xmwX9uwU8huxPAAgM8WBb0xzsHe3xoTj-lrm96YkJlJk_fkUYjk7V_r7gGz_NHygjD32TAzKHCTK2vORscZqkPjXTbz6CuUJ1LtA82mzop_7yCYsbKr5o6hDOq3Ig_jtTMkwOJG7iqkxaI_p6DX9uPl1WS9crobV_yX8Eu6N_6CEGQRW4wDLj452Mc1AjpdGeDU1RufUbGKkUl_WawcngITCgJeu1PrmDKBrrRLVGKGhlMsn-7vGbXAt5xgEfo1G9X0NKRu7jQDr9WO7kUK3UHy6_QyhhNzxGROGbKqj-NX3BsWte02z2BGGRAaPUWcFj0KORVk6CfjIv1Cgdxw","expires_in":"3600","token_type":"bearer","user":{"user":{"contact":{"email":{"address":"q011@mychangjie.com","verified":true},"sms":{"verifiedNumber":"+8613328461381","verifiedNumberCountry":"CN","verificationRequired":false}},"dob":{"day":3,"month":2,"year":1992},"gender":"M","language":"zh-Hans","location":{"country":"CN"},"marketing":{"dataShares":{"thirdParty":false},"email":true,"sms":true},"name":{"latin":{"family":"kj","given":"大飞"}},"nuId":"7623794448c34cb5b44c50a943b6b00e","registration":{"siteId":"nikedotcom","timestamp":1608612849243},"screenname":"大飞k614797386","screenNameAutoGenerated":true,"social":{"allowTagging":false,"locationVisibility":"PRIVATE","socialVisibility":"SOCIAL"},"upmId":"07833e4b-59e6-4826-8ec8-fa06661f516c","userType":"MEMBER"},"address":[{"id":"8ADFC44F53C44F969BDE8AC9442948BE","code":"212000","country":"CN","line1":"L万达广场写字楼A座6280号","locality":"镇江市","name":{"primary":{"family":"李","given":"蕞腑"}},"phone":{"primary":"15358605207"},"preferred":true,"province":"CN-32","region":"润州区","zone":"润州区"}]},"timestamp":"1610884612","clientId":"HlHa2Cje3ctlaOqnxvgZXNaAs7T9nAuH","uxId":"com.nike.commerce.nikedotcom.web","lastLoginTime":"1610884612918"}

    token = driver.execute_script("return localStorage.getItem('com.nike.commerce.nikedotcom.web.credential')")
    # driver.close()
    return token





if __name__ == "__main__":
    name = 'q010@mychangjie.com'
    pass_w = 'Qq123456'
    tokenTry = get_token(name, pass_w)
    dict_try = json.loads(tokenTry)
    # print(type(dict_try))
    # 过滤tokenTry
    clientId = dict_try.get('clientId')
    access_token = dict_try.get('access_token')

    # print(clientId)
    # print(access_token)

    #模板格式输出
    print(name + ',' + pass_w + ',' + clientId + ',' + access_token)



